databases:
  - name: event_harbor
    databaseName: event_harbor_db
    user: event_harbor_db_user
    plan: free

services:
  - type: web
    name: event_harbor
    runtime: ruby
    plan: free
    buildCommand: './bin/render-build.sh'

    startCommand: './bin/rails server'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: event_harbor
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false